name: auto-study

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop, master ]
  schedule:
    - cron: 0 6 * * 3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
    
    - name: Pip requirements
      run:
        pip3 install requests pycryptodome gmssl
         
    - name: auto study
      env:
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PWD}}
        pubKey: ${{secrets.PUB_KEY}}
        ocrSecret: ${{secrets.OCR_SECRET_KEY}}
        ocrKey: ${{secrets.OCR_API_KEY}}
        ocrType: ${{secrets.OCR_TYPE}}
        sendType: ${{secrets.SEND_TYPE}}
        sendKey: ${{secrets.SEND_KEY}}
        sendMode: ${{secrets.SEND_MODE}}
        userId: ${{secrets.USER_ID}}
        accessToken: ${{secrets.ACCESS_TOKEN}}
        apiUrl: ${{secrets.API_URL}}
      run:
        python3 workflow.py
        
