name: auto-study

on:
  workflow_dispatch:
  
  pull_request:
    branches: [ develop, master ]
  schedule:
    - cron: 0 6 * * 2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install requirements
      run: pip install -r requirements.txt
         
    - name: Auto study
      env:
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PWD}}
        pubKey: ${{secrets.PUB_KEY}}
        ocrSecret: ${{secrets.OCR_SECRET_KEY}}
        ocrKey: ${{secrets.OCR_API_KEY}}
        ocrType: ${{secrets.OCR_TYPE}}
        sendType: ${{secrets.SEND_TYPE}}
        sendKey: ${{secrets.SEND_KEY}}
        sendMode: ${{secrets.SEND_MODE}}
        extUsers: ${{secrets.EXT_USERS}}
      run:
        python3 workflow.py
        
